baseurl = "https://tracker.learn.cisco/docs"
languageCode = "en-us"
title = "Tracker Docs"
theme = "hugo-theme-learn"
MetaDataFormat = "yaml"

[params]
  editURL = "https://github.com/rajasoun/tracker.doc/tree/master/content"
  description = "Documentation for Tracker"
  author = "Raja. S"
  autoNav = true
  search = true
