baseurl = "https://tracker.learn.cisco/"
languageCode = "en-us"
title = "Tracker Docs"
theme = "hugo-theme-learn"
MetaDataFormat = "yaml"

[params]
  editURL = "https://github.com/rajasoun/ignitor/docs/tracker/edit/master/content/"
  description = "Documentation for Tracker"
  author = "Raja. S"
  autoNav = true
  search = true
